name: Demanejar ShortURL

title: URLDemanejar ShortURL
description: Demanejar platform help short url

version: v0.2

baseurl: ""
permalink: /:slug/
logo: /assets/logo_dmr99.png

theme: jekyll-theme-minimal

plugins:
  - jekyll-redirect-from

collections:
  urls:
    output: true
    permalink: /:slug

whitelist:
  - jekyll-redirect-from

redirect_from:
  json: false

include:
  - _urls

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
